name: CI + SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 跑测试并生成 JaCoCo 报告
      - name: Build & Test (JaCoCo)
        run: mvn -B clean verify

      # 通过 Maven Sonar 插件上报结果（使用你在 SonarCloud 设置的组织/项目）
      - name: Sonar analysis (Maven)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=LinLing1030_StudyLifeAPI \
            -Dsonar.organization=linling1030 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.coverage.exclusions=src/main/webapp/**,src/main/webapp/js/**,src/main/webapp/css/**,src/main/webapp/**/*.html
