name: CI + SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      # ❶ 生成 JaCoCo 覆盖率报告 (target/site/jacoco/jacoco.xml)
      - name: Build & Test (with JaCoCo)
        run: mvn -B clean verify

      # ❷ Sonar 扫描，并指向 jacoco.xml
      # ❸ 可选：临时排除前端/Servlet 覆盖率，减少 "Lines to cover" 压力
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=LinLing1030_StudyLifeAPI
            -Dsonar.organization=linling1030
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.coverage.exclusions=src/main/webapp/**,src/main/webapp/js/**,src/main/webapp/css/**,src/main/webapp/**/*.html
