name: CI + SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      # 预热依赖，降低首次构建失败概率
      - name: Warm up Maven dependencies
        run: |
          mvn -B -U \
            -Dmaven.wagon.http.retryHandler.count=5 \
            -Dmaven.wagon.http.pool=false \
            dependency:go-offline

      - name: Build & Test
        run: |
          mvn -B clean verify \
            -Dmaven.wagon.http.retryHandler.count=5 \
            -Dmaven.wagon.http.pool=false

      - name: SonarCloud Scan (Maven)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dmaven.wagon.http.retryHandler.count=5 \
            -Dmaven.wagon.http.pool=false
