name: CI + SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 用 JDK 11，满足你项目里 enforcer 的 [11,12] 约束
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build & Test (JaCoCo)
        run: mvn -B clean verify

      - name: Sonar analysis (Maven)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B -DskipTests \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=LinLing1030_StudyLifeAPI \
            -Dsonar.organization=linling1030 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.coverage.exclusions="src/main/webapp/**,src/main/webapp/js/**,src/main/webapp/css/**,src/main/webapp/**/*.html"
